### ISSUE TITLE
Docker login before compose pull

### ISSUE THREAD

**Issue by febalist** [mbecker20/monitor#40]
During the deploy stack process, I encounter an “access forbidden” error at the compose pull stage:
![CleanShot 2024-08-20 at 09 51 34@2x](https://github.com/user-attachments/assets/3d245360-5573-4195-ab3a-674a2345ae7b)

It looks like docker login isn’t happening before compose pull, even though config.registry_account is set up.

In the code, I noticed that in /bin/periphery/src/compose.rs, docker login happens after compose pull. It might need to be swapped to ensure login happens first.

Core 1.13.3
Periphery 1.13.3

**Comment by mbecker20** [comment]
You are correct, thanks for the Report! Fixed in this commit: [https://github.com/mbecker20/monitor/commit/a2758ce6f4c557b52ec8acb49e929648c4d48c91](https://github.com/mbecker20/monitor/commit/a2758ce6f4c557b52ec8acb49e929648c4d48c91)

I'm building 1.13.4 now to address this issue, will release shortly. Thanks for your interest in the project!

**Comment by febalist** [comment]
Thank you for the quick fix! The project looks incredibly useful and convenient.
