### ISSUE TITLE
Leading "." in run directory causes deploy to fail

### ISSUE THREAD

**Issue by cantchooseaname8** [mbecker20/monitor#45]
When pulling from GitHub, having a leading "." in the run directory causes it to fail when deploying. Removing the "." without making any other changes makes it work just fine. Here's a screenshot of where I'm referring to.
<img width="717" alt="Screenshot 2024-08-23 at 7 25 38 PM" src="https://github.com/user-attachments/assets/14ccb3eb-c386-4d09-aa32-622531c0b597">

**Comment by mbecker20** [comment]
For a Git Repo based Stack, the run directory should be relative to to the **root of the Git repo**.

For example, this is a repo holding some compose files for the demo, eg immich.compose.yaml: [https://git.demo.monitor.dev/mbecks/demo-sync](https://git.demo.monitor.dev/mbecks/demo-sync)

The run directory for this repo should just be `.` or `./` since the compose files are in the root folder of the git repo.
Monitor can just `cd <repo_dir> && docker compose -f immich.compose.yaml up -d`. 

Even if you have the file in some **folder in the repo**, you can usually leave the run directory as `./`, and instead just change the File Path to ./folder_name/immich.compose.yaml.

But what if you have a Monorepo with maybe some code in it, and in Extra Args you add `--build`?
This will tell Monitor to clone the repo, **build the code into an image**, and then deploy the stack. Docker builds depend on build context, which depends on the current working directory of where the command is called. For this reason, Monitor provides this custom Run Directory feature, to change to the correct working directory to run the docker compose command, and build the images correctly.

If this is not your intention, just leave the Run Directory as `./` and specify the relative path to the compose file as I described above.

Hope this helps!

**Comment by cantchooseaname8** [comment]
Makes sense. Thanks for the explanation. I'm still learning all of this, but I appreciate your help (both here and on reddit)
